### ISSUE TITLE
Add to documentation how to add Kaggle json

### ISSUE THREAD

**Issue by VojtechCermak** [WildlifeDatasets/wildlife-datasets#1]
import json
!touch ~/.kaggle/kaggle.json
api_token = {“username”:“XXXXX”,“key”:“XXXXXX”}
with open(‘/root/.kaggle/kaggle.json’, ‘w’) as file:
    json.dump(api_token, file)
!chmod 600 ~/.kaggle/kaggle.json

**Comment by sadda** [comment]
There is a description in the [documentation](https://wildlifedatasets.github.io/wildlife-datasets/preprocessing/#kaggle) with a link to the description at Kaggle.
