### ISSUE TITLE
Column date has wrong type

### ISSUE THREAD

**Issue by mfruhner** [WildlifeDatasets/wildlife-datasets#2]
Hello,
I am testing your new Toolkit and I encountered an error when loading the SeaTurtleIDHeads Dataset:

`Exception: Column date has wrong type. Allowed types = ['date']`

Any idea?
Thanks!

**Comment by mfruhner** [comment]
I fixed it by changing line 1153 in datasets.py to:

`df['date'] = df['date'].apply(lambda x: datetime.datetime.strptime(x[:10], "%Y:%m:%d"))`

**Comment by sadda** [comment]
Thank you, it is now fixed :)
