### ISSUE TITLE
Request for including the original dataset publications.

### ISSUE THREAD

**Issue by MatthiasZuerl** [WildlifeDatasets/wildlife-datasets#5]
It would be very helpful if the information about the original publication were included in the dataset overview [documentation](https://wildlifedatasets.github.io/wildlife-datasets/datasets/). You should be able to access that information without installing the package first or browsing through this cumbersome [table](https://github.com/WildlifeDatasets/wildlife-datasets/blob/main/wildlife_datasets/datasets/metadata.csv).

**Comment by sadda** [comment]
Sure, no problem. Is including link as [in here](https://wildlifedatasets.github.io/wildlife-datasets/preprocessing/) sufficient? If not, please write how you would like to see it :)

**Comment by MatthiasZuerl** [comment]
I would prefer the respective publication over a link, as it typically contains the most information (data collection methodology, analyses, etc.). However, since not all datasets are associated with a publication, a link should likely suffice as well. Thanks for the quick response! :)

**Comment by sadda** [comment]
Give me one week or so, the documentation including publications is ready but not yet present on the main branch. So far, you can check the links to the publications in the `publication_url` column of the [cumbersome table](https://github.com/WildlifeDatasets/wildlife-datasets/blob/datasets/wildlife_datasets/datasets/summary.csv) as you like to call it ;)

**Comment by sadda** [comment]
In the end, it was much faster. The publications are now available both [here](https://wildlifedatasets.github.io/wildlife-datasets/datasets/) and [here](https://wildlifedatasets.github.io/wildlife-datasets/preprocessing/).

I am closing the issue, if you are not satisfied, please reopen it.

**Comment by MatthiasZuerl** [comment]
Appreciated, thank you so much! :-)
